"use client";

import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Loading from "./loading";
import { useState, useEffect } from "react";
import { type Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate a loading delay
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 2000); // Adjust delay as needed

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <body>
        {isLoading ? (
          <Loading />
        ) : (
          <TRPCReactProvider>
            <Navbar />
            {children}
            <Footer />
          </TRPCReactProvider>
        )}
      </body>
    </html>
  );
}
